/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* hdlname = "\\SOC" *)
(* top =  1  *)
(* src = "leds.v:3.1-41.10" *)
module SOC(CLK, LEDS);
  (* src = "leds.v:4.14-4.17" *)
  input CLK;
  wire CLK;
  (* hdlname = "CW CLK" *)
  (* src = "leds.v:33.21-37.5|clockworks.v:3.11-3.14" *)
  wire \CW.CLK ;
  (* hdlname = "CW DIV_CLK" *)
  (* src = "leds.v:33.21-37.5|clockworks.v:4.11-4.18" *)
  wire \CW.DIV_CLK ;
  (* force_downto = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:51.21-51.22" *)
  wire [21:0] \CW.DIV_CLK_SB_LUT4_I2_I3 ;
  (* force_downto = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:33.26-33.27" *)
  wire [21:0] \CW.DIV_CLK_SB_LUT4_I2_O ;
  (* hdlname = "CW slow_CLK" *)
  (* src = "leds.v:33.21-37.5|clockworks.v:9.17-9.25" *)
  wire [21:0] \CW.slow_CLK ;
  (* src = "leds.v:5.20-5.24" *)
  output [4:0] LEDS;
  wire [4:0] LEDS;
  (* src = "leds.v:11.9-11.16" *)
  wire div_clk;
  (* src = "leds.v:10.14-10.18" *)
  wire [4:0] leds;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] leds_SB_DFFSR_Q_R;
  (* unused_bits = "4" *)
  wire [4:0] leds_SB_DFF_Q_D;
  (* src = "leds.v:9.14-9.16" *)
  wire [4:0] pc;
  (* force_downto = 32'd1 *)
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:33.23-33.24" *)
  wire [4:0] pc_SB_DFFSR_Q_4_D;
  (* force_downto = 32'd1 *)
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:33.26-33.27" *)
  wire [4:0] pc_SB_DFFSR_Q_D;
  (* force_downto = 32'd1 *)
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:51.21-51.22" *)
  wire [4:0] pc_SB_DFFSR_Q_D_SB_LUT4_O_I3;
  wire pc_SB_DFFSR_Q_R;
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.DIV_CLK_SB_DFF_Q  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [21]),
    .Q(div_clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(div_clk),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [21]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [5]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [5]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_1  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [4]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [4]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_10  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [15]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [15]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_11  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [14]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [14]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_12  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [13]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [13]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_13  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [12]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [12]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_14  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [11]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [11]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_15  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [10]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [10]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_16  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [9]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [9]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_17  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [8]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [8]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_18  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [7]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [7]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_19  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [6]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [6]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_2  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [3]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [3]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_20  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(\CW.slow_CLK [0]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_3  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [2]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [2]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_4  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [20]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [20]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_5  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [1]),
    .I3(\CW.slow_CLK [0]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_6  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [19]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [19]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_7  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [18]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [18]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_8  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [17]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [17]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \CW.DIV_CLK_SB_LUT4_I2_O_SB_LUT4_O_9  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\CW.slow_CLK [16]),
    .I3(\CW.DIV_CLK_SB_LUT4_I2_I3 [16]),
    .O(\CW.DIV_CLK_SB_LUT4_I2_O [16])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_CI  (
    .CI(\CW.slow_CLK [0]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [2]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [1])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [9]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [10]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [9])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_1  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [8]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [9]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [8])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_10  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [18]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [19]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [18])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_11  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [17]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [18]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [17])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_12  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [16]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [17]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [16])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_13  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [15]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [16]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [15])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_14  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [14]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [15]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [14])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_15  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [13]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [14]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [13])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_16  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [12]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [13]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [12])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_17  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [11]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [12]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [11])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_18  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [10]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [11]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [10])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_2  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [7]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [8]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [7])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_3  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [6]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [7]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [6])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_4  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [5]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [6]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [5])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_5  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [4]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [5]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [4])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_6  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [3]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [4]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [3])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_7  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [2]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [3]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [2])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_8  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [20]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [21]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [20])
  );
  (* src = "leds.v:33.21-37.5|clockworks.v:11.19-11.31|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \CW.slow_CLK_SB_CARRY_I1_9  (
    .CI(\CW.DIV_CLK_SB_LUT4_I2_I3 [19]),
    .CO(\CW.DIV_CLK_SB_LUT4_I2_I3 [20]),
    .I0(1'h0),
    .I1(\CW.slow_CLK [19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [20]),
    .Q(\CW.slow_CLK [20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_1  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [19]),
    .Q(\CW.slow_CLK [19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_10  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [10]),
    .Q(\CW.slow_CLK [10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_11  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [9]),
    .Q(\CW.slow_CLK [9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_12  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [8]),
    .Q(\CW.slow_CLK [8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_13  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [7]),
    .Q(\CW.slow_CLK [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_14  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [6]),
    .Q(\CW.slow_CLK [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_15  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [5]),
    .Q(\CW.slow_CLK [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_16  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [4]),
    .Q(\CW.slow_CLK [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_17  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [3]),
    .Q(\CW.slow_CLK [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_18  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [2]),
    .Q(\CW.slow_CLK [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_19  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [1]),
    .Q(\CW.slow_CLK [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_2  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [18]),
    .Q(\CW.slow_CLK [18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_20  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [0]),
    .Q(\CW.slow_CLK [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_3  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [17]),
    .Q(\CW.slow_CLK [17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_4  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [16]),
    .Q(\CW.slow_CLK [16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_5  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [15]),
    .Q(\CW.slow_CLK [15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_6  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [14]),
    .Q(\CW.slow_CLK [14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_7  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [13]),
    .Q(\CW.slow_CLK [13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_8  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [12]),
    .Q(\CW.slow_CLK [12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:33.21-37.5|clockworks.v:10.4-12.7|/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \CW.slow_CLK_SB_DFF_Q_9  (
    .C(CLK),
    .D(\CW.DIV_CLK_SB_LUT4_I2_O [11]),
    .Q(\CW.slow_CLK [11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/ff_map.v:19.59-19.105" *)
  SB_DFFSR leds_SB_DFFSR_Q (
    .C(div_clk),
    .D(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .Q(LEDS[4]),
    .R(leds_SB_DFFSR_Q_R[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0100)
  ) leds_SB_DFFSR_Q_R_SB_LUT4_I0 (
    .I0(leds_SB_DFFSR_Q_R[0]),
    .I1(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .I2(pc_SB_DFFSR_Q_4_D[1]),
    .I3(pc_SB_DFFSR_Q_4_D[4]),
    .O(pc_SB_DFFSR_Q_R)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h3000)
  ) leds_SB_DFFSR_Q_R_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .I2(leds_SB_DFFSR_Q_R[0]),
    .I3(pc_SB_DFFSR_Q_4_D[1]),
    .O(leds_SB_DFF_Q_D[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0ff)
  ) leds_SB_DFFSR_Q_R_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(pc_SB_DFFSR_Q_4_D[3]),
    .I3(pc_SB_DFFSR_Q_4_D[2]),
    .O(leds_SB_DFFSR_Q_R[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF leds_SB_DFF_Q (
    .C(div_clk),
    .D(leds_SB_DFF_Q_D[3]),
    .Q(LEDS[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF leds_SB_DFF_Q_1 (
    .C(div_clk),
    .D(leds_SB_DFF_Q_D[2]),
    .Q(LEDS[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF leds_SB_DFF_Q_2 (
    .C(div_clk),
    .D(leds_SB_DFF_Q_D[1]),
    .Q(LEDS[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF leds_SB_DFF_Q_3 (
    .C(div_clk),
    .D(leds_SB_DFF_Q_D[0]),
    .Q(LEDS[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h000e)
  ) leds_SB_DFF_Q_D_SB_LUT4_O (
    .I0(pc_SB_DFFSR_Q_4_D[3]),
    .I1(pc_SB_DFFSR_Q_4_D[2]),
    .I2(pc_SB_DFFSR_Q_4_D[1]),
    .I3(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .O(leds_SB_DFF_Q_D[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1c00)
  ) leds_SB_DFF_Q_D_SB_LUT4_O_1 (
    .I0(pc_SB_DFFSR_Q_4_D[2]),
    .I1(pc_SB_DFFSR_Q_4_D[3]),
    .I2(pc_SB_DFFSR_Q_4_D[1]),
    .I3(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .O(leds_SB_DFF_Q_D[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc100)
  ) leds_SB_DFF_Q_D_SB_LUT4_O_2 (
    .I0(pc_SB_DFFSR_Q_4_D[2]),
    .I1(pc_SB_DFFSR_Q_4_D[1]),
    .I2(pc_SB_DFFSR_Q_4_D[3]),
    .I3(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .O(leds_SB_DFF_Q_D[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:28.4-31.7|/usr/bin/../share/yosys/ice40/ff_map.v:19.59-19.105" *)
  SB_DFFSR pc_SB_DFFSR_Q (
    .C(div_clk),
    .D(pc_SB_DFFSR_Q_D[4]),
    .Q(pc_SB_DFFSR_Q_4_D[4]),
    .R(pc_SB_DFFSR_Q_R)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:28.4-31.7|/usr/bin/../share/yosys/ice40/ff_map.v:19.59-19.105" *)
  SB_DFFSR pc_SB_DFFSR_Q_1 (
    .C(div_clk),
    .D(pc_SB_DFFSR_Q_D[3]),
    .Q(pc_SB_DFFSR_Q_4_D[3]),
    .R(pc_SB_DFFSR_Q_R)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:28.4-31.7|/usr/bin/../share/yosys/ice40/ff_map.v:19.59-19.105" *)
  SB_DFFSR pc_SB_DFFSR_Q_2 (
    .C(div_clk),
    .D(pc_SB_DFFSR_Q_D[2]),
    .Q(pc_SB_DFFSR_Q_4_D[2]),
    .R(pc_SB_DFFSR_Q_R)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:28.4-31.7|/usr/bin/../share/yosys/ice40/ff_map.v:19.59-19.105" *)
  SB_DFFSR pc_SB_DFFSR_Q_3 (
    .C(div_clk),
    .D(pc_SB_DFFSR_Q_D[1]),
    .Q(pc_SB_DFFSR_Q_4_D[1]),
    .R(pc_SB_DFFSR_Q_R)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:28.4-31.7|/usr/bin/../share/yosys/ice40/ff_map.v:19.59-19.105" *)
  SB_DFFSR pc_SB_DFFSR_Q_4 (
    .C(div_clk),
    .D(pc_SB_DFFSR_Q_D[0]),
    .Q(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .R(pc_SB_DFFSR_Q_R)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) pc_SB_DFFSR_Q_4_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .O(pc_SB_DFFSR_Q_D[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) pc_SB_DFFSR_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(pc_SB_DFFSR_Q_4_D[4]),
    .I3(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[4]),
    .O(pc_SB_DFFSR_Q_D[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) pc_SB_DFFSR_Q_D_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(pc_SB_DFFSR_Q_4_D[3]),
    .I3(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[3]),
    .O(pc_SB_DFFSR_Q_D[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) pc_SB_DFFSR_Q_D_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(pc_SB_DFFSR_Q_4_D[2]),
    .I3(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[2]),
    .O(pc_SB_DFFSR_Q_D[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) pc_SB_DFFSR_Q_D_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(pc_SB_DFFSR_Q_4_D[1]),
    .I3(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .O(pc_SB_DFFSR_Q_D[1])
  );
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY pc_SB_DFFSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO (
    .CI(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[3]),
    .CO(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[4]),
    .I0(1'h0),
    .I1(pc_SB_DFFSR_Q_4_D[3])
  );
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY pc_SB_DFFSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_1 (
    .CI(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[2]),
    .CO(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[3]),
    .I0(1'h0),
    .I1(pc_SB_DFFSR_Q_4_D[2])
  );
  (* src = "leds.v:30.31-30.37|/usr/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY pc_SB_DFFSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_2 (
    .CI(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1]),
    .CO(pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[2]),
    .I0(1'h0),
    .I1(pc_SB_DFFSR_Q_4_D[1])
  );
  assign \CW.CLK  = CLK;
  assign \CW.DIV_CLK  = div_clk;
  assign \CW.DIV_CLK_SB_LUT4_I2_I3 [1] = \CW.slow_CLK [0];
  assign \CW.DIV_CLK_SB_LUT4_I2_I3 [0] = 1'h0;
  assign \CW.slow_CLK [21] = div_clk;
  assign leds[4] = LEDS[4];
  assign leds[3] = LEDS[3];
  assign leds[2] = LEDS[2];
  assign leds[1] = LEDS[1];
  assign leds[0] = LEDS[0];
  assign leds_SB_DFFSR_Q_R[3] = pc_SB_DFFSR_Q_4_D[4];
  assign leds_SB_DFFSR_Q_R[2] = pc_SB_DFFSR_Q_4_D[1];
  assign leds_SB_DFFSR_Q_R[1] = pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1];
  assign pc[4] = pc_SB_DFFSR_Q_4_D[4];
  assign pc[3] = pc_SB_DFFSR_Q_4_D[3];
  assign pc[2] = pc_SB_DFFSR_Q_4_D[2];
  assign pc[1] = pc_SB_DFFSR_Q_4_D[1];
  assign pc[0] = pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[1];
  assign pc_SB_DFFSR_Q_4_D[0] = pc_SB_DFFSR_Q_D[0];
  assign pc_SB_DFFSR_Q_D_SB_LUT4_O_I3[0] = 1'h0;
endmodule
